data:
  # large configuration
  wav: /home/nj/projects/music/data/dset/combined22k 
  samplerate: 44100
  datasr: 22050
  segment: 9    # 11
  shift: 0.5
  channels: 2
  normalize: true
  metadata: ./metadata
  # sources: ['drums', 'bass', 'other', 'vocals']
  sources: ['mix', 'vocals']
    # arglist: ['pitch', 'reverb']
  arglist: ['pitch']

ema:
  epoch: [0.9, 0.95]
  batch: [0.9995, 0.9999]

model:
  # sources: ['drums', 'bass', 'other', 'vocals']
  sources: ['mix', 'vocals']
  audio_channels: 2
  # Main structure
  dims: [4, 64, 128, 256]
  # STFT
  nfft: 4096     # 4096
  hop_size: 1024
  win_size: 4096     # 4096
  normalized: True
  # SD/SU layer
  # band_SR: [0.225, 0.372, 0.403]     
  band_SR: [0.333, 0.3333, 0.334]     
  band_stride: [1, 4, 16]             
  band_kernel: [3, 4, 16]                  
  # Convolution Module
  conv_depths: [3,2,1]
  compress: 4 
  conv_kernel: 3
  # Dual-path RNN
  num_dplayer: 6
  expand: 1
  freq_reduce: true

epochs: 200
batch_size: 8    # 8

optim:
  # lr: 0.0003
  lr: 0.0001
  decay_rate: 0.98
  decay_step: 10
  momentum: 0.9
  beta2: 0.999
  optim: adam
  weight_decay: 0
  # loss: 'vocal'
  loss: 'mix'

seed: 42
save_every:

augment:
  shift_same: false
  remix:
    proba: 1
    group_size: 4
  scale:
    proba: 1
    min: 0.25
    max: 1.25
  flip: true

misc:
  num_workers: 6
